version: '2'

services:
  elasticsearch:
    image: elasticsearch:2.3.4
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:2.3.4-1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logstash/config:/etc/logstash/conf.d
      - /tmp/data:/var/log/httpd
    ports:
      - "5000:5000"
    links:
      - elasticsearch

  kibana:
    build:
      context: ./kibana
      #args:
      #  http_proxy: http://proxy.example.com
      #  https_proxy: http://proxy.example.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
